defaultProject: "beta-toolkit-martech"
defaultLocation: "US"
defaultDataset: "martech_refined"
defaultAssertionDataset: "martech_assertions"
vars:
  flavor: "full"
  raw_ga4_dataset: "raw_ga4"
  raw_ads_dataset: "raw_ads"
  raw_ads_table: "ad_CampaignBasicStats_987654321"