main:
  params: [args]
  steps:
    - init:
        assign:
          # Variáveis injetadas pelo Terraform (Cifrão Simples)
          - repository: "projects/${project_id}/locations/${region}/repositories/${repository}"

    - compile_dataform:
        call: http.post
        args:
          url: $${"https://dataform.googleapis.com/v1beta1/" + repository + "/compilationResults"}
          auth:
            type: OAuth2
          body:
            gitCommitish: "main"
            codeCompilationConfig:
              vars:
                flavor: "${flavor}"
                lookback_days: "${lookback_days}"
        result: compilation_result

    - run_invocation:
        try:
          steps:
            - create_invocation:
                call: http.post
                args:
                  url: $${"https://dataform.googleapis.com/v1beta1/" + repository + "/workflowInvocations"}
                  auth:
                    type: OAuth2
                  body:
                    compilationResult: $${compilation_result.body.name}
                    invocationConfig:
                      includedTags: ["${flavor}"]
                      transitiveDependenciesIncluded: true
                result: invocation

            - wait_for_completion:
                call: http.get
                args:
                  url: $${"https://dataform.googleapis.com/v1beta1/" + invocation.body.name}
                  auth:
                    type: OAuth2
                result: invocation_status

            - check_status:
                switch:
                  - condition: $${invocation_status.body.state == "RUNNING"}
                    next: wait_for_completion
                  - condition: $${invocation_status.body.state != "SUCCEEDED"}
                    raise: "Workflow invocation failed"
        
        retry: # Tenta novamente em caso de erro temporário de rede
          attempts: 2
          backoff:
            initial_delay: 60
            multiplier: 2

        # Se houver erro ou falha de Assertion, o Workflow "cai" aqui
        except:
          as: e
          steps:
            - prepare_error_data:
                assign:
                  - error_payload:
                      # Variáveis exclusivas do Workflow usam Cifrão Duplo ($$)
                      message: $${e.message} 
                      # Variáveis do Terraform usam Cifrão Simples ($)
                      flavor: "${flavor}"
                      project: "${project_id}"
            - publish_to_pubsub:
                call: googleapis.pubsub.v1.projects.topics.publish
                args:
                  topic: "projects/${project_id}/topics/martech-v9-alerts"
                  body:
                    messages:
                      - data: $${base64.encode(json.encode_to_string(error_payload))}