config { 
  type: "table", 
  schema: data.gold_schema,
  name: data.tab_gld_mkt,
  disabled: !data.enable_marketing 
}
SELECT
  COALESCE(g.data, a.data) AS data,
  COALESCE(g.campanha, a.campanha) AS campanha,
  SUM(g.sessoes) AS sessoes,
  SUM(a.custo) AS investimento
FROM (SELECT data, campanha, COUNT(DISTINCT session_id) AS sessoes FROM ${ref(data.tab_slv_ga4)} GROUP BY 1,2) g
FULL OUTER JOIN (SELECT data, campanha, custo FROM ${ref(data.tab_slv_ads)}) a USING (data, campanha)
GROUP BY 1,2